{{- if .Values.backend.enabled -}}
{{- if ge ( .Values.backend.replicas | int ) 1 }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "activly.name" . }}-backend
  labels:
    app: {{ include "activly.name" . }}
    tier: backend
    version: {{ .Chart.AppVersion }}
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: {{ include "activly.name" . }}
      tier: backend
  template:
    metadata:
      labels:
        app: {{ include "activly.name" . }}
        tier: backend
        version: {{ .Chart.AppVersion }}
      {{ with .Values.backend.podLabels }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
      annotations:
      {{ with .Values.backend.podAnnotations }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
        - name: {{ include "activly.name" . }}-backend
          image:  {{ include "activly.images.image" ( dict "imageRoot" .Values.backend.image "root" $ ) }}
          imagePullPolicy: {{ .Values.backend.image.pullPolicy | default .Values.global.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.backend.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
          env:
            {{- include "activly.postgres.env" ( dict "root" $ ) | nindent 12 }}
          ports:
            - containerPort: {{ .Values.backend.port }}
          {{- if .Values.backend.probes.liveness.enabled }}
          livenessProbe:
            httpGet:
              port: {{ .Values.backend.port }}
              path: "/live"
            initialDelaySeconds: {{ .Values.backend.probes.liveness.initialDelaySeconds | default 10 }}
            periodSeconds: {{ .Values.backend.probes.liveness.periodSeconds | default 10 }}
            timeoutSeconds: {{ .Values.backend.probes.liveness.timeoutSeconds | default 1 }}
            successThreshold: {{ .Values.backend.probes.liveness.successThreshold | default 1 }}
            failureThreshold: {{ .Values.backend.probes.liveness.successThreshold | default 3 }}
          {{- end }}
          {{- if .Values.backend.probes.readiness.enabled }}
          readinessProbe:
            httpGet:
              port: {{ .Values.backend.port }}
              path: "/ready"
            initialDelaySeconds: {{ .Values.backend.probes.readiness.initialDelaySeconds | default 10 }}
            periodSeconds: {{ .Values.backend.probes.readiness.periodSeconds | default 10 }}
            timeoutSeconds: {{ .Values.backend.probes.readiness.timeoutSeconds | default 1 }}
            successThreshold: {{ .Values.backend.probes.readiness.successThreshold | default 1 }}
            failureThreshold: {{ .Values.backend.probes.readiness.successThreshold | default 3 }}
          {{- end }}
{{- end -}}
{{- end -}}