apiVersion: v1
kind: Service
metadata:
  name: {{ include "activly.name" . }}-backend
spec:
  ports:
    - port: {{ .Values.backend.port }}
  selector:
      app: {{ include "activly.name" . }}
      tier: backend
  type: ClusterIP
