apiVersion: apps/v1
kind: Deployment
metadata:
  name: activly-backend
  labels:
    app: activly
    tier: backend
spec:
  selector:
    matchLabels:
      app: activly
      tier: backend
  template:
    metadata:
      labels:
        app: activly
        tier: backend
    spec:
      containers:
      - name: activly-backend
        image: activly-backend
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 5149 # FIXME: this is for Tilt, change to > 10000, same as in Dockerfile
#          readOnlyRootFilesystem: true # ← probably not good for Tilt
          capabilities:
            drop:
              - "ALL"
        resources:
          limits:
            cpu: "1"
            memory: "200Mi"
          requests:
            cpu: "0.2"
            memory: "100Mi"
        env:
          - name: "POSTGRES_HOST"
            value: "postgres"
          - name: "POSTGRES_PORT"
            value: "5432"
          - name: "POSTGRES_DB"
            valueFrom:
              configMapKeyRef:
                name: "db"
                key: "name"
          - name: "POSTGRES_USER"
            valueFrom:
              configMapKeyRef:
                name: "db"
                key: "user"
          - name: "POSTGRES_PASSWORD"
            valueFrom:
              secretKeyRef:
                name: "db"
                key: "password"
        ports:
        - containerPort: 8080
