---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "db"
data:
  name: "activly"
  user: "activly"

---
apiVersion: v1
kind: Secret
metadata:
  name: "db"
type: Opaque
data:
  password: "YWN0aXYxeQ=="  # pragma: allowlist secret

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "postgres"
  labels:
    app: "postgres"
    tier: "db"
spec:
  selector:
    matchLabels:
      app: "postgres"
      tier: "db"
  serviceName: "postgres"
  template:
    metadata:
      labels:
        app: "postgres"
        tier: "db"
    spec:
      containers:
      - name: "postgres"
        image: "postgres:16.1-alpine3.19"
#        securityContext:
#          allowPrivilegeEscalation: false
#          runAsNonRoot: true
#          runAsUser: 25432
          # readOnlyRootFilesystem: true  ← probably not good for Tilt
          # capabilities:
          #  drop:
          #    - "ALL"
          #  add:
          #    - "CAP_CHOWN"
          #    - "CAP_FOWNER"
          #    - "CAP_FSETID"
        resources:
          limits:
            cpu: "1"
            memory: "200Mi"
          requests:
            cpu: "0.2"
            memory: "100Mi"
        env:
          - name: "POSTGRES_DB"
            valueFrom:
              configMapKeyRef:
                name: "db"
                key: "name"
          - name: "POSTGRES_USER"
            valueFrom:
              configMapKeyRef:
                name: "db"
                key: "user"
          - name: "POSTGRES_PASSWORD"
            valueFrom:
              secretKeyRef:
                name: "db"
                key: "password"
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: "postgres"
  labels:
    app: "postgres"
    tier: "db"
spec:
  selector:
    app: "postgres"
    tier: "db"
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
