apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgresql.auth.existingSecret }}
  labels:
    app: {{ include "activly.name" . }}
    tier: backend
    version: {{ .Chart.AppVersion }}

type: Opaque
stringData:
  {{ .Values.postgresql.auth.secretKeys.adminPasswordKey }}: {{ randAlphaNum ( .Values.global.auth.passwordLength | int ) }}
  {{ .Values.postgresql.auth.secretKeys.userPasswordKey }}: {{ randAlphaNum ( .Values.global.auth.passwordLength | int ) }}
