name: Build & Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_n_test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Set up Go 1.x
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
        id: go
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -coverprofile=coverage.out -v ./...
      - name: Report test coverage to DeepSource
        uses: deepsourcelabs/test-coverage-action@master
        with:
          coverage-file: coverage.out
          key: "go"
          dsn: ${{ secrets.DEEPSOURCE_DSN }}
      - name: Report test coverage to Codacy
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          coverage-reports: coverage.out
          force-coverage-parser: "go"
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}